name: Bazil Stander
favicon: null
layout_spectrum: 0.1393337135668844
typography_spectrum: 0.07386538037098944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5462972754612565
  lightness: 0.4721563784405589
  saturation: 0.7987834445666522
  rhythmicContrast: 0.28149970318190753
purpose: []
